### ISSUE TITLE
Problem loging in from the app

### ISSUE THREAD

**Issue by tcarlyle** [SINTEF-SIT/emht-app#19] opened 2015-07-13 13:09 UTC
I've noticed what seems to be 2 problems with the log in.

1) If I try to change the url in the log-in gui, the log in fails. It displayed an error about the server url being /78.91.98.234:19000/ without the http.

I've changed the strings.xml in the source so that both urls in the default_server_url and login_url_dev pointed to the server here, and then I did not get that error anylonger.

2) But then, I seem to get a username/password error:

07-13 14:38:42.012  20137-20328/? W/ServerAuthenticate﹕ looking for cookie
07-13 14:38:42.017  20137-20328/? W/ServerAuthenticate﹕ session: null
07-13 14:38:42.017  20137-20328/? W/System.err﹕ android.accounts.AuthenticatorException: Username and/or password is incorrect
07-13 14:38:42.027    3009-3011/? D/dalvikvm﹕ GC_CONCURRENT freed 914K, 31% free 10275K/14728K, paused 4ms+5ms, total 48ms
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at sintef.android.emht.account.ServerAuthenticate.userSignIn(ServerAuthenticate.java:64)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at sintef.android.emht.account.AuthenticatorActivity$2.doInBackground(AuthenticatorActivity.java:85)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at sintef.android.emht.account.AuthenticatorActivity$2.doInBackground(AuthenticatorActivity.java:75)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
07-13 14:38:42.037  20137-20328/? W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
07-13 14:38:42.037  20137-20328/? W/AuthenticatorActivity﹕ Username and/or password is incorrect

**Comment by iverasp** [comment] 2015-07-14 08:07
default_server_url is only used in the layout for the login activity when setting the initial text in the url textview. login_url_dev is not used anywhere.

The error message will display the url without the http even though it has been provided. If no http is provided it will show "Protocol not found (...)".

I will try different approaches but so far I'm unable to reproduce this error...

**Comment by iverasp** [comment] 2015-07-14 10:16
fixed in latest commit

**Closed as completed by iverasp** 2015-07-14 10:16 UTC
