### ISSUE TITLE
Error when receiving a new GCM

### ISSUE THREAD

**Issue by tcarlyle** [SINTEF-SIT/emht-app#16] opened 2015-07-08 07:34 UTC
I just tried assigning an alarm to an operator, but it did not work.

As per the log, it seems to be some error when receiving the gcm:

07-08 09:31:22.141    8551-9245/? W/EMHTGcmListenerService﹕ GCM recieved message: sintef.android.emht.gcm.new_assignment
07-08 09:31:22.641   8551-10781/? W/System.err﹕ sintef.android.emht.sync.RestAPIClient$BadRequestException: Bad request
07-08 09:31:22.661   8551-10781/? W/System.err﹕ at sintef.android.emht.sync.RestAPIClient.exceptionHandler(RestAPIClient.java:85)
07-08 09:31:22.661   8551-10781/? W/System.err﹕ at sintef.android.emht.sync.RestAPIClient.post(RestAPIClient.java:54)
07-08 09:31:22.661   8551-10781/? W/System.err﹕ at sintef.android.emht.sync.SyncAdapter.sendAlarms(SyncAdapter.java:100)
07-08 09:31:22.661   8551-10781/? W/System.err﹕ at sintef.android.emht.sync.SyncAdapter.onPerformSync(SyncAdapter.java:60)

**Comment by iverasp** [comment] 2015-07-08 07:39
Could you please provide the server log as well?

**Comment by tcarlyle** [comment] 2015-07-08 07:50
[debug] application - Successfull authentication from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - GCM Dispatch alarm notification: {"registration_ids":["ftfbuzwKBOM:APA91bEbM5Kn1TJ66eIEkPgzvdS5YDeM7xd4puFnRxOuyI_lS-c13Cl9g_sEsuhCIxpx7siqVs_kGw-NNTs2jANM_qM3n4a2fXzuLakqDZg0lHPiYPcfjSgtWp4waARq43p8KJVONNJd"],"data":{"message":"sintef.android.emht.gcm.new_assignment"}}
[debug] application - GCM Response: {"multicast_id":8745355075555943346,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1436340542705867%f21b41e4f9fd7ecd"}]}
[debug] application - Location report from: mario
[debug] application - [EVENT] Firing Event [ALARM_NEW] models.Alarm@e null null
[debug] application - GCM Dispatch alarm notification: {"registration_ids":["ftfbuzwKBOM:APA91bEbM5Kn1TJ66eIEkPgzvdS5YDeM7xd4puFnRxOuyI_lS-c13Cl9g_sEsuhCIxpx7siqVs_kGw-NNTs2jANM_qM3n4a2fXzuLakqDZg0lHPiYPcfjSgtWp4waARq43p8KJVONNJd"],"data":{"message":"sintef.android.emht.gcm.new_assignment"}}
[debug] application - GCM Response: {"multicast_id":5991394067472855125,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1436340680873536%f21b41e4f9fd7ecd"}]}
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - [EVENT] Firing Event [ALARM_NEW] models.Alarm@f null null
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario
[debug] application - Location report from: mario

**Comment by iverasp** [comment] 2015-07-08 07:59
I'm unable to reproduce this issue atm. My best bet so far is that there is something wrong with the json syntax that is sent to the server (onPerformSync -> sendAlarms -> post).

To clarify what the GCM message sintef.android.emht.gcm.new_assignment does atm: When recieved the GCM listener triggers a sync. The sync first tries to upload all the finished alarms, then downloads all new alarms and if applicable, uploads it's GCM reg id.

**Comment by iverasp** [comment] 2015-07-08 11:09
This was caused by an encoding error. Fix has been pushed to master.

**Closed as completed by iverasp** 2015-07-08 11:09 UTC
